DROP DATABASE IF EXISTS 442Battleship;
CREATE DATABASE IF NOT EXISTS 442Battleship;
USE 442Battleship;

CREATE USER IF NOT EXISTS 'battleship_usr'@'localhost' IDENTIFIED BY 'B@TTLESH1P';
GRANT SELECT, UPDATE, CREATE, INSERT ON 442Battleship.* TO 'battleship_usr'@'localhost';
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS Users (
    UID INT AUTO_INCREMENT NOT NULL,
    fName VARCHAR(255) NOT NULL,
    lName VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    hPass VARCHAR(255) NOT NULL,
    PRIMARY KEY (UID)
);

CREATE TABLE IF NOT EXISTS Chats (
    ID INT NOT NULL,
    fromUser INT NOT NULL,
    content VARCHAR(255) NOT NULL,
    datestamp DATETIME NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (fromUser) REFERENCES Users(UID)
);